"""Generate offline prompt inputs for an LLM baseline.

Goal
----
Provide a *reproducible* way to build prompt context without calling any external API.
The user can paste the generated prompt into any LLM UI and then save the returned
partition as JSON under:
  results/llm_baseline/cached/<system>_llm_prompt_partition.json

Then evaluate via:
  python scripts/multimodal/phase4/run_llm_baseline_cached.py <system>

This script optionally enriches each class with top keywords extracted from
semantic embeddings (when `data/processed/embedding/<system>_class_embeddings.json` exists).

Output
------
- results/llm_baseline/prompts/<system>_prompt.txt
- results/llm_baseline/prompts/<system>_prompt_meta.json

The meta file records the class list and keyword provenance.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Optional


ROOT = Path(__file__).resolve().parents[3]


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _get_class_order(system: str) -> List[str]:
    p = ROOT / "data" / "processed" / "fusion" / f"{system}_class_order.json"
    if not p.exists():
        raise FileNotFoundError(f"Missing class_order: {p}")
    return _load_json(p)


def _get_gt_k(system: str) -> Optional[int]:
    p = ROOT / "data" / "processed" / "groundtruth" / f"{system}_ground_truth.json"
    if not p.exists():
        return None
    gt = _load_json(p)
    labels = []
    if isinstance(gt, dict):
        # common formats: {class: label} or {service: [classes...]}
        if all(isinstance(v, (int, float, str)) for v in gt.values()):
            labels = list(gt.values())
        elif all(isinstance(v, list) for v in gt.values()):
            labels = list(gt.keys())
    if not labels:
        return None
    return len(set(labels))


def _load_top_keywords(system: str, topk: int) -> Dict[str, List[str]]:
    """Best-effort: load per-class keywords from class embeddings json.

    Expected file generated by semantic pipeline:
      data/processed/embedding/<system>_class_embeddings.json

    Each item typically contains:
      {"class": "pkg.Foo", "embedding": [...], "keywords": [...]}   (keywords optional)

    If keywords are missing, returns empty mapping.
    """
    p = ROOT / "data" / "processed" / "embedding" / f"{system}_class_embeddings.json"
    if not p.exists():
        return {}
    data = _load_json(p)
    out: Dict[str, List[str]] = {}
    if isinstance(data, list):
        for item in data:
            if not isinstance(item, dict):
                continue
            cls = item.get("class")
            kws = item.get("keywords") or item.get("top_keywords")
            if isinstance(cls, str) and isinstance(kws, list):
                out[cls] = [str(x) for x in kws[:topk]]
    return out


def _build_prompt(system: str, classes: List[str], *, gt_k: Optional[int], kws: Dict[str, List[str]], topk: int) -> str:
    k_line = f"K={gt_k}" if gt_k is not None else "K=UNKNOWN"
    header = (
        f"You are given a list of Java classes from the legacy system '{system}'.\n"
        f"Task: partition the classes into microservices (clusters).\n"
        f"If possible, target the ground-truth service count ({k_line}).\n\n"
        "Output format STRICTLY as JSON mapping from fully-qualified class name to an integer cluster_id.\n"
        "Example: {\"com.a.Foo\": 0, \"com.a.Bar\": 0, \"com.b.Baz\": 1}\n"
        "Requirements:\n"
        "- cluster_id must be integer starting from 0\n"
        "- every class in the list must appear exactly once\n"
        "- do not include any extra keys\n\n"
    )

    lines = [header, "CLASSES:\n"]
    for c in classes:
        if kws.get(c):
            lines.append(f"- {c}  | keywords: {', '.join(kws[c][:topk])}\n")
        else:
            lines.append(f"- {c}\n")

    lines.append(
        "\nNow produce only the JSON mapping (no markdown, no commentary).\n"
    )
    return "".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--system", required=True)
    ap.add_argument("--topk", type=int, default=5, help="Top keywords per class to include when available")
    ap.add_argument("--limit", type=int, default=250, help="Optional cap on number of classes (for token budget); 0=all")
    args = ap.parse_args()

    system = str(args.system).lower().strip()
    classes = _get_class_order(system)
    if args.limit and int(args.limit) > 0:
        classes = classes[: int(args.limit)]

    gt_k = _get_gt_k(system)
    kws = _load_top_keywords(system, int(args.topk))

    prompt = _build_prompt(system, classes, gt_k=gt_k, kws=kws, topk=int(args.topk))

    out_dir = ROOT / "results" / "llm_baseline" / "prompts"
    out_dir.mkdir(parents=True, exist_ok=True)

    prompt_path = out_dir / f"{system}_prompt.txt"
    meta_path = out_dir / f"{system}_prompt_meta.json"

    prompt_path.write_text(prompt, encoding="utf-8")
    meta_path.write_text(
        json.dumps(
            {
                "system": system,
                "gt_k": gt_k,
                "num_classes": len(classes),
                "class_order_path": str((ROOT / "data" / "processed" / "fusion" / f"{system}_class_order.json").relative_to(ROOT)).replace("\\", "/"),
                "keywords_source": str((ROOT / "data" / "processed" / "embedding" / f"{system}_class_embeddings.json").relative_to(ROOT)).replace("\\", "/")
                if (ROOT / "data" / "processed" / "embedding" / f"{system}_class_embeddings.json").exists()
                else None,
                "topk": int(args.topk),
                "limit": int(args.limit),
            },
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )

    print(f"[OK] wrote: {prompt_path}")
    print(f"[OK] wrote: {meta_path}")


if __name__ == "__main__":
    main()
