# Reproduce CONFIDE (ICSME 2026) main results (Table III/IV + main figures)
#
# Usage (PowerShell, repo root):
#   .\scripts\reproduce_paper.ps1 -Tag paper_v1
#
# Notes:
# - Assumes you have created/activated a Python environment and installed dependencies.
# - If results/paper_snapshot/<Tag>/ exists, this script copies that snapshot back
#   to canonical data/processed paths.
# - Otherwise, it uses the canonical data/processed files already present in the repo.

[CmdletBinding()]
param(
  [string]$Tag = "paper_v1"
)

$ErrorActionPreference = "Stop"

function Assert-FileExists([string]$Path) {
  if (-not (Test-Path -LiteralPath $Path)) {
    throw "Missing required path: $Path"
  }
}

Write-Host "[CONFIDE] Reproduce paper results" -ForegroundColor Cyan
Write-Host "  Tag: $Tag" -ForegroundColor Cyan
Write-Host "  Root: $(Get-Location)" -ForegroundColor Cyan

# --- Step 0: materialize canonical inputs when a snapshot is available ---
# Snapshot source (generated by scripts/multimodal/phase4/snapshot_paper_inputs.py)
$snapRoot = Join-Path -Path "results\paper_snapshot" -ChildPath $Tag
$src = Join-Path -Path $snapRoot -ChildPath "data\processed"
$dst = "data\processed"

if (Test-Path -LiteralPath $snapRoot) {
  if (-not (Test-Path -LiteralPath $src)) {
    throw "Snapshot is present but missing expected folder: $src"
  }

  Write-Host "[Step 0] Copy snapshot -> canonical data/processed/..." -ForegroundColor Yellow
  Copy-Item -Recurse -Force (Join-Path $src "*") $dst
} else {
  Write-Host "[Step 0] No snapshot found at $snapRoot; using existing data/processed/ inputs." -ForegroundColor Yellow
  Assert-FileExists "data\processed\fusion\acmeair_class_order.json"
  Assert-FileExists "data\processed\groundtruth\acmeair_ground_truth.json"
}

# --- Step 1: Phase3 partitions ---
Write-Host "[Step 1] Phase3 (CAC + baselines) partitions" -ForegroundColor Yellow
python scripts\multimodal\phase3\phase3_cac_evaluation.py acmeair daytrader jpetstore plants

# --- Step 2: Table III ---
Write-Host "[Step 2] Table III (overall comparison)" -ForegroundColor Yellow
python scripts\multimodal\phase4\run_mono_baselines_and_ours_table.py daytrader plants acmeair jpetstore
python scripts\multimodal\phase4\make_all_systems_mono_table.py
python scripts\multimodal\phase4\generate_paper_final_table.py

# --- Step 3: Table IV ---
Write-Host "[Step 3] Table IV (diagnosis)" -ForegroundColor Yellow
python scripts\multimodal\phase4\generate_table_IV_regress_diagnosis.py

# --- Step 4: Figures ---
Write-Host "[Step 4] Main figures" -ForegroundColor Yellow
python scripts\multimodal\phase4\plot_semantic_smoothing_bar_median_iqr.py
python scripts\multimodal\phase4\plot_semantic_pdf_dade.py

Write-Host "[DONE] Key outputs:" -ForegroundColor Green
$outs = @(
  "results\ablation\baseline\paper_final_table.csv",
  "results\ablation\baseline\paper_final_table.md",
  "results\artifact_tables\table_IV_regress_diagnosis.csv",
  "results\artifact_tables\table_IV_regress_diagnosis.md"
)
foreach ($p in $outs) {
  if (Test-Path -LiteralPath $p) {
    $fi = Get-Item -LiteralPath $p
    Write-Host ("  OK  {0}  ({1} bytes)" -f $p, $fi.Length) -ForegroundColor Green
  } else {
    Write-Host ("  MISS {0}" -f $p) -ForegroundColor Red
  }
}

Write-Host "[DONE] Figures (if generated by scripts):" -ForegroundColor Green
if (Test-Path -LiteralPath "results\paper") {
  Write-Host "  - results\\paper\\" -ForegroundColor Green
}
if (Test-Path -LiteralPath "results\plots") {
  Write-Host "  - results\\plots\\" -ForegroundColor Green
}
