"""Reset and re-run the multimodal pipeline in a reproducible way.

Goals
- Delete *derived* artifacts (Phase1/2/3 outputs) so historical runs don't affect results.
- Preserve raw inputs (raw code, traces, JTL, ground truth).
- Re-run Phase1 (matrices), Phase2 (EDL uncertainty) and Phase3 (CAC) consistently.

This script is intentionally conservative: it only deletes known derived folders/files.

Usage (Windows PowerShell):
  python scripts/multimodal/reset_and_rerun_pipeline.py --system all --reset
  python scripts/multimodal/reset_and_rerun_pipeline.py --system acmeair --reset --run

Typical full rerun:
  python scripts/multimodal/reset_and_rerun_pipeline.py --system all --reset --run \
    --phase2_run_tag 2026-02-01_u_robust --u_norm robust --autotune

Notes
- Phase2 requires an EDL model checkpoint and scaler. If missing, this script can optionally train.
- This script does not touch:
  - data/raw/**
  - results/jmeter/** (JTL)
  - data/processed/traces/**
  - data/processed/groundtruth/**
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path


SYSTEMS = ["acmeair", "daytrader", "jpetstore", "plants"]


def _run(cmd: list[str], cwd: Path) -> None:
    print("\n[CMD]", " ".join(cmd))
    subprocess.check_call(cmd, cwd=str(cwd))


def _safe_rmtree(path: Path) -> None:
    if not path.exists():
        return
    if path.is_dir():
        shutil.rmtree(path)
        print(f"[RESET] Removed dir: {path}")
    else:
        path.unlink(missing_ok=True)
        print(f"[RESET] Removed file: {path}")


def reset_outputs(root: Path, systems: list[str]) -> None:
    """Remove derived artifacts but keep raw/inputs."""
    processed = root / "data" / "processed"

    # Phase2 outputs
    _safe_rmtree(processed / "edl")

    # Phase1/Phase3 outputs (selective)
    fusion_dir = processed / "fusion"
    for sys in systems:
        # matrices/partitions/cache generated by our pipeline
        patterns = [
            f"{sys}_S_*.npy",
            f"{sys}_S_final.npy",
            f"{sys}_S_sem_embedding.npy",
            f"{sys}_classes.json",
            f"{sys}_class_order.json",
            f"{sys}_baseline_partition.json",
            f"{sys}_cac-final_partition.json",
            f"{sys}_cac_params.json",
        ]
        for pat in patterns:
            for p in fusion_dir.glob(pat):
                _safe_rmtree(p)

    # Temporal matrices are derived (but cheap), reset them too
    temporal_dir = processed / "temporal"
    for sys in systems:
        for p in temporal_dir.glob(f"{sys}_S_temp.npy"):
            _safe_rmtree(p)


def run_phase1(root: Path, systems: list[str], py: str) -> None:
    # These scripts were used in this workspace to build alignment and fused matrices.
    # Build class index + order + matrices.
    # NOTE: if a system name mismatch exists, you may need to adjust here.
    for sys in systems:
        _run([py, "scripts/multimodal/phase1/build_class_index.py", sys], cwd=root)
        _run([py, "scripts/multimodal/phase1/build_class_order.py", sys], cwd=root)
        _run([py, "scripts/multimodal/phase1/build_multimodal_matrices.py", sys], cwd=root)


def _resolve_phase2_artifacts(
    root: Path,
    system: str,
    *,
    model_path: str | None,
    scaler_path: str | None,
    run_tag: str | None
):
    """Resolve model/scaler paths.

    Priority:
      1) explicit --phase2_model/--phase2_scaler (can contain '{system}')
      2) run_tag: data/processed/edl/runs/<tag>/checkpoints/<system>_edl_model.pt + <system>_scaler.pkl
      3) canonical: data/processed/edl/<system>_edl_model.pt + <system>_scaler.pkl
    """

    if model_path:
        mp = Path(model_path.format(system=system))
        if not mp.is_absolute():
            mp = root / mp
    else:
        mp = None

    if scaler_path:
        sp = Path(scaler_path.format(system=system))
        if not sp.is_absolute():
            sp = root / sp
    else:
        sp = None

    if mp and sp:
        return mp, sp

    if run_tag:
        base = root / "data" / "processed" / "edl" / "runs" / run_tag
        mp2 = base / "checkpoints" / f"{system}_edl_model.pt"
        sp2 = base / "checkpoints" / f"{system}_scaler.pkl"
        if mp is None:
            mp = mp2
        if sp is None:
            sp = sp2

    if mp is None:
        mp = root / "data" / "processed" / "edl" / f"{system}_edl_model.pt"
    if sp is None:
        sp = root / "data" / "processed" / "edl" / f"{system}_scaler.pkl"

    return mp, sp


def run_phase2_infer(
    root: Path,
    systems: list[str],
    py: str,
    *,
    u_norm: str,
    run_tag: str | None,
    phase2_model: str | None,
    phase2_scaler: str | None,
) -> None:
    """Run Phase2 inference only.

    This assumes you already have model+scaler and Phase1 artifacts.
    """

    for sys in systems:
        model, scaler = _resolve_phase2_artifacts(root, sys, model_path=phase2_model, scaler_path=phase2_scaler, run_tag=run_tag)
        if not model.exists() or not scaler.exists():
            raise FileNotFoundError(
                f"Missing Phase2 model/scaler for {sys}: {model} / {scaler}. "
                f"Provide --phase2_model/--phase2_scaler, or --phase2_run_tag, or copy files into data/processed/edl/."
            )

        class_order = root / "data" / "processed" / "fusion" / f"{sys}_class_order.json"

        emb = root / "data" / "processed" / "fusion" / f"{sys}_S_sem_embedding.npy"
        s_struct = root / "data" / "processed" / "fusion" / f"{sys}_S_struct.npy"
        s_sem = root / "data" / "processed" / "fusion" / f"{sys}_S_sem_dade_base.npy"
        s_temp = root / "data" / "processed" / "temporal" / f"{sys}_S_temp.npy"

        cmd = [
            py,
            "scripts/multimodal/phase2/edl_infer.py",
            "--emb",
            str(emb),
            "--s_struct",
            str(s_struct),
            "--s_sem",
            str(s_sem),
            "--s_temp",
            str(s_temp),
            "--model",
            str(model),
            "--scaler",
            str(scaler),
            "--class_order",
            str(class_order),
            "--system",
            sys,
            "--u_norm",
            u_norm,
        ]
        if run_tag:
            cmd += ["--run_tag", run_tag]
        _run(cmd, cwd=root)

        # Copy the final U into the canonical location expected by Phase3
        # If run_tag is used, the output is in runs/<tag>/infer_outputs/{sys}_edl_uncertainty.npy
        if run_tag:
            u_src = root / "data" / "processed" / "edl" / "runs" / run_tag / "infer_outputs" / f"{sys}_edl_uncertainty.npy"
        else:
            # fallback (edl_infer default without run_dir may not place it here)
            u_src = root / "edl_uncertainty.npy"
        u_dst_dir = root / "data" / "processed" / "edl"
        u_dst_dir.mkdir(parents=True, exist_ok=True)
        u_dst = u_dst_dir / f"{sys}_edl_uncertainty.npy"
        shutil.copy2(u_src, u_dst)
        print(f"[PHASE2] Copied U: {u_src} -> {u_dst}")


def run_phase3(root: Path, systems: list[str], py: str, *, autotune: bool) -> None:
    cmd = [py, "scripts/multimodal/phase3/phase3_cac_evaluation.py", *systems]
    if autotune:
        cmd += ["--autotune", "--autotune_budget", "fast"]
    _run(cmd, cwd=root)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--system", default="all", help="System name or 'all'")
    parser.add_argument("--reset", action="store_true")
    parser.add_argument("--run", action="store_true")

    # Phase2 options
    parser.add_argument("--u_norm", default="robust", choices=["none", "minmax", "robust", "quantile"])
    parser.add_argument("--phase2_run_tag", default=None, help="If set, also try locating model/scaler under data/processed/edl/runs/<tag>/checkpoints")
    parser.add_argument("--phase2_model", default=None, help="Explicit model path (can include '{system}' placeholder)")
    parser.add_argument("--phase2_scaler", default=None, help="Explicit scaler path (can include '{system}' placeholder)")
    parser.add_argument("--skip_phase2", action="store_true", help="Skip Phase2 inference (useful to reset+Phase1 only).")

    # Phase3 options
    parser.add_argument("--autotune", action="store_true")

    args = parser.parse_args()

    root = Path(__file__).resolve().parents[2]
    py = str(root / ".venv" / "Scripts" / "python.exe")

    systems = SYSTEMS if args.system == "all" else [args.system]

    if args.reset:
        reset_outputs(root, systems)

    if args.run:
        run_phase1(root, systems, py)
        if not args.skip_phase2:
            run_phase2_infer(
                root,
                systems,
                py,
                u_norm=args.u_norm,
                run_tag=args.phase2_run_tag,
                phase2_model=args.phase2_model,
                phase2_scaler=args.phase2_scaler,
            )
        run_phase3(root, systems, py, autotune=bool(args.autotune))


if __name__ == "__main__":
    main()
